WebView/Comanda.Webview/Models/Comanda.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Comanda.Webview.Models
{
    public class Comanda
    {
        public string id { get; set; }

        public int idProduto { get; set; }

        public int qtidadeItem { get; set; }

        public List<Produto> listaProdutos { get; set; }

        public Comanda()
        {
            listaProdutos = new List<Produto>();
        }
    }
}

WebView/Comanda.Webview/Models/Produto.cs
namespace Comanda.Webview.Models
{
    public class Produto
    {
        public int id { get; set; }

        public string descricao { get; set; }

        public double valor { get; set; }

        public int estoque { get; set; }
    }
}

WebView/Comanda.Webview/Controllers/ComandaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Comanda.Webview.Controllers
{
    public class ComandaController : Controller
    {
        private List<Models.Comanda> ListaProdutos = new List<Models.Comanda>();

        // GET: Comanda
        public ActionResult Index()
        {
            return View();
        }

        // GET: Comanda/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comanda/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comanda/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comanda/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comanda/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comanda/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comanda/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public void InserePedidoMemoria(string comanda, int idProduto, int qtdadeItem)
        {
            ListaProdutos.Add(new Models.Comanda() { id = comanda,  idProduto=idProduto, qtidadeItem = qtdadeItem});
        }
    }
}

WebView/Comanda.Webview/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Comanda.Webview.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebView/Comanda.Webview/Views/Comanda/Create.cshtml
@model Comanda.Webview.Models.Comanda

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="row separator">
                <div class="input-field col s12">
                    @Html.TextBoxFor(model => model.id, new { htmlAttributes = new { @class = "validate" } })
                    @Html.ValidationMessageFor(model => model.qtidadeItem, "", new { @class = "red-text" })
                    <label for="comanda">Comanda</label>
                </div>
            </div>


            <div class="row separator">
                <ul class="collection">
                    <li class="collection-item dismissable row">
                        <div class="col s4 center-align" id="pedido">Café</div>
                        <div class="col s4 center-align">Valor</div>
                        <div class="col s4"><a href="#!" class="secondary-content" onclick="javascript:insereQtdade()"><i class="material-icons">send</i></a></div>
                    </li>
                </ul>
            </div>
            @Html.LabelFor(model => model.qtidadeItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qtidadeItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qtidadeItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Fechar" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div id="tblListar">

    </div>
}

@*<script language="javascript">

    var tbPedidos = localStorage.getItem("tbClientes");// Recupera os dados armazenados
        tbPedidos = JSON.parse(tbPedidos); // Converte string para objeto

        if (tbPedidos == null) // Caso não haja conteúdo, iniciamos um vetor vazio
            tbPedidos = [];


    function insereQtdade() {
        var qtdade = prompt("Quantidade", 1);

        var pedido = JSON.stringify({
            Comanda: $("#id").val(),
            Pedido: $("#pedido").text(),
            Quantidade: qtdade
        });

        tbPedidos.push(pedido);
        localStorage.setItem("tbClientes", JSON.stringify(tbPedidos));
        alert("Registro adicionado.");
        Listar();
        return true;

        $(".hpedidos").append("<div id='comanda'");

        $.ajax({
            url: '@Url.Action("InserePedidoMemoria", "Comanda")',
            data: { comanda: 1, idProduto: 2, qtdadeItem: 3 }
        }).done(function () {
            alert('Added');
        });
        }

    function Listar() {
        $("#tblListar").html("");
        $("#tblListar").html(
            "<thead>" +
            "	<tr>" +
            "	<th>Comanda</th>" +
            "	<th>Pedido</th>" +
            "	<th>Quantidade</th>" +
            "	</tr>" +
            "</thead>" +
            "<tbody>" +
            "</tbody>"
        );
        for (var i in tbPedidos) {
            var cli = JSON.parse(tbPedidos[i]);
            $("#tblListar tbody").append("<tr>");
            $("#tblListar tbody").append("<td>" + cli.Comanda + "</td>");
            $("#tblListar tbody").append("<td>" + cli.Pedido + "</td>");
            $("#tblListar tbody").append("<td>" + cli.Quantidade + "</td>");
            $("#tblListar tbody").append("</tr>");
        }
    }

</script>*@

WebView/Comanda.Webview/Views/Comanda/Index.cshtml
@model IEnumerable<Comanda.Webview.Models.Comanda>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.qtidadeItem)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.qtidadeItem)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

WebView/Comanda.Webview/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebView/Comanda.Webview/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebView/Comanda.Webview/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row meio-tela">
    <form class="col s12">
        <div class="row">
            <div class="input-field col s12 valign-wrapper">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" class="validate">
                <label for="icon_prefix">Usuário</label>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <input id="password" type="password" class="validate">
                <label for="password">Senha</label>
            </div>
        </div>
    </form>
</div>

WebView/Comanda.Webview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="blue darken-2">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo"><img class="brand-logo-img" src="~/Imagens/logo.png"/></a>
            <a href="#" data-activates="mobile-demo-login" class="button-collapse"><i class="material-icons">menu</i></a>

            @*Ativar esse menu quando estiver logado*@
            <ul class="side-nav" id="mobile-demo-logout">
                <li>@Html.ActionLink("Sair", "Index", "Home")</li>
                <li>@Html.ActionLink("Ajuda", "Index", "Home")</li>
            </ul>

            <ul class="side-nav" id="mobile-demo-login">
                <li>@Html.ActionLink("Entrar", "Index", "Home")</li>
                <li>@Html.ActionLink("Ajuda", "Index", "Home")</li>
            </ul>
        </div>
    </nav>
   
    @if (User.Identity.IsAuthenticated)
    {
        @RenderBody()
    }
    else
    {
        <div>
            <ul id="tabs-swipe-demo" class="tabs separator">
                <li class="tab col s3 "><a class="active  blue-text text-darken-2 " href="#test-swipe-1">Novo</a></li>
                <li class="tab col s3"><a class="blue-text text-darken-2 " href="#test-swipe-2">Consulta</a></li>
                <li class="tab col s3"><a class="blue-text text-darken-2 " href="#test-swipe-3">Test 3</a></li>
            </ul>
            <div id="test-swipe-1" class="col s12">@RenderBody()</div>
            <div id="test-swipe-2" class="col s12 red">Test 2</div>
            <div id="test-swipe-3" class="col s12 green">Test 3</div>
        </div>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)
</body>
</html>